version: "3.8"

services:
  MeTube.User-DB: #Konfiguration för databasen
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: MeTube.User-DB
    hostname: MeTube.User-DB
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    restart: always
    volumes:
      - MeTube.User-Volume:/var/opt/mssql  #Länkar till en volym för att spara databasen

  MeTube.User: #Skapar och konfigurerar Imagen
    build:
      context: ./
      dockerfile: Metube.UserService/UserService/Dockerfile
    container_name: MeTube.User
    ports:
      - "5000:5000"
    environment:
      - METUBE_USER_SERVICE_PORT=5000
      - METUBE_USER_SERVICE_CONNECTION_STRING=Server=MeTube.User-DB,1433;Database=MeTubeUserDb;User Id=sa;Password=${DB_PASSWORD};Encrypt=Yes;TrustServerCertificate=Yes;
    depends_on:
      - MeTube.User-DB
    restart: always
    volumes:
      - ./:/src  #Synkar hela projektmappen med containern för live kodändringar

volumes:
  MeTube.User-Volume:
    driver: local
