version: "3.8"

services:
  MeTube.User-DB:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: MeTube.User-DB
    hostname: MeTube.User-DB
    ports:
      - "${DB_PORT}:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    restart: always
    volumes:
      - MeTube.User-Volume:/var/opt/mssql

  MeTube.User:
    build:
      context: ./
      dockerfile: dockerfile-development
    container_name: MeTube.User
    ports:
      - "${APP_PORT}:5000"
    environment:
      - DefaultConnection=${DB_CONNECTION_STRING}
    depends_on:
      - MeTube.User-DB
    restart: always
    volumes:
      - ./:/src
    env_file:
      - .env

volumes:
  MeTube.User-Volume:
    driver: local
