version: "3.8"

services:
  # metube-user-db:
  #   image: mcr.microsoft.com/mssql/server:2022-latest
  #   container_name: metube-user-db
  #   hostname: metube-user-db
  #   ports:
  #     - "1444:1433"
  #   environment:
  #     - ACCEPT_EULA=Y
  #     - SA_PASSWORD=YourSecretPass123
  #   restart: always
  #   volumes:
  #     - metube-user-volume:/var/opt/mssql

  metube-user:
    build:
      context: .
      dockerfile: dockerfile-development
    container_name: metube-user
    ports:
      - "5000:5000"
    environment:
      - DB_CONNECTION_STRING=Server=metube-user-db,1433;Database=MeTubeUserDb;User Id=sa;Password=YourSecretPass123;TrustServerCertificate=True
    restart: always
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  metube-user-volume:
    driver: local
