version: "3.8"

services:
  MeTube.User-DB: #Konfiguration för databasen
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: MeTube.User-DB
    hostname: MeTube.User-DB
    ports:
      - "${DB_PORT}:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASSWORD}
    restart: always
    volumes:
      - MeTube.User-Volume:/var/opt/mssql  #Länkar till en volym för att spara databasen

  MeTube.User: #Skapar och konfigurerar Imagen
    build:
      context: ./
      dockerfile: Metube.UserService/UserService/Dockerfile
    container_name: MeTube.User
    ports:
     - "${APP_PORT}:5000"
    environment:
      - DefaultConnection=${DB_CONNECTION_STRING}
    depends_on:
      - MeTube.User-DB
    restart: always
    volumes:
      - ./:/src  #Synkar hela projektmappen med containern för live kodändringar
    env_file:
      - .env
volumes:
  MeTube.User-Volume:
    driver: local
