FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app
EXPOSE 80
COPY ./*.sln ./
COPY ./MeTube-DevOps.UserManagement/*.csproj ./MeTube-DevOps.UserManagement/
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app/out . 

RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"
ENTRYPOINT ["dotnet", "watch", "run", "--no-launch-profile", "--project", "MeTube-DevOps.UserManagement"]
