@MeTube_DevOps_UserManagement_HostAddress = http://localhost:5178

GET {{MeTube_DevOps_UserManagement_HostAddress}}/api/User
Accept: application/json

###
POST {{MeTube_DevOps_UserManagement_HostAddress}}/api/User/signup
Content-Type: application/json

{
  "username": "testuser1",
  "password": "password1",
  "email": "test1@example.com",
  "role": "Admin"
}
###
