FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app
EXPOSE 80
COPY ./*.sln ./
COPY ./MeTube-DevOps.UserService/*.csproj ./MeTube-DevOps.UserService/
COPY ./MeTube-DevOps.UserService.UnitTests/*.csproj ./MeTube-DevOps.UserService.UnitTests/
COPY ./MeTube-DevOps.UserService.IntegrTests/*.csproj ./MeTube-DevOps.UserService.IntegrTests/
RUN ["dotnet","restore"]

COPY . .
ENV ASPNETCORE_ENVIRONMENT=Development

CMD ["dotnet","watch","run","--no-launch-profile","--project","MeTube-DevOps.UserService"]