services:
  metube-user-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: metube-user-db
    hostname: metube-user-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourSecretPass123
    healthcheck:
      test:
        [
          "CMD",
          "sqlcmd",
          "-S",
          "localhost",
          "-U",
          "sa",
          "-P",
          "YourSecretPass123",
          "-Q",
          "SELECT 1",
        ]
      interval: 10s
      retries: 5
    restart: always
    volumes:
      - metube-user-volume:/var/opt/mssql

  metube-user:
    image: userservice:1
    build:
      context: .
      dockerfile: Dockerfile-User-dev
    container_name: metube-user
    ports:
      - "5000:8080"
    environment:
      - DB_CONNECTION_STRING=Server=metube-user-db,1433;Database=MeTubeUserDb;User Id=sa;Password=YourSecretPass123;TrustServerCertificate=True
    restart: always
    volumes:
      - ./data:/app/data
    depends_on:
      - metube-user-db

volumes:
  metube-user-volume:
    driver: local
