FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
EXPOSE 80

COPY ./*.sln ./
COPY ./MeTube-DevOps.UserService/*.csproj ./MeTube-DevOps.UserService/
COPY ./MeTube-DevOps.UserService.UnitTests/*.csproj ./MeTube-DevOps.UserService.UnitTests/
COPY ./MeTube-DevOps.UserService.IntegrTests/*.csproj ./MeTube-DevOps.UserService.IntegrTests/

RUN dotnet restore

COPY ./MeTube-DevOps.UserService .
RUN dotnet publish -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app
EXPOSE 80
COPY --from=build /app/publish .
RUN dotnet tool install --global dotnet-ef
ENV PATH="${PATH}:/root/.dotnet/tools"

ENTRYPOINT ["dotnet", "/app/MeTube-DevOps.UserService.dll"]