# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  metubedevopsuserservice:
    image: metubedevopsuserservice
    build:
      context: .
      dockerfile: MeTube-DevOps.UserService/MeTube-DevOps.UserService/Dockerfile
    ports:
      - 5218:5218
