FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app
EXPOSE 80
COPY ./*.sln ./
COPY ./MeTube-Client/*.csproj ./MeTube-Client/

RUN dotnet restore

COPY . .
RUN dotnet publish -c Release -o out

WORKDIR /app
RUN ["dotnet","restore"]
ENTRYPOINT ["dotnet","/app/MeTube.Client.dll"]