FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /app

# Kopiera och återställ beroenden
COPY ./*.sln ./
COPY ./MeTube-Client/*.csproj ./MeTube-Client/
RUN dotnet restore

# Kopiera all kod och bygg projektet
COPY . . 
RUN dotnet publish -c Release -o /app/out

# Använd en lättviktig runtime-image
FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app

# Kopiera utgångsfilerna från build-steget
COPY --from=build /app/out .

# Ändra ENTRYPOINT till ditt nya DLL-namn
ENTRYPOINT ["dotnet", "MeTube-Client.dll"]
