FROM mcr.microsoft.com/dotnet/sdk:9.0
WORKDIR /app
EXPOSE 80
COPY ./*.sln ./
COPY ./MeTube-Gateway/*.csproj ./MeTube-Gateway/
# COPY ./Flixtube.Gateway.UnitTests/*.csproj ./Flixtube.Gateway.UnitTests/
# COPY ./Flixtube.Gateway.IntegrationTests/*.csproj ./Flixtube.Gateway.IntegrationTests/
RUN ["dotnet","restore"]
CMD ["dotnet","watch","run","--no-launch-profile","--project","Flixtube.Gateway"]