FROM mcr.microsoft.com/dotnet/sdk:9.0

EXPOSE 80
WORKDIR /app

# Kopiera lösningsfil
COPY ./*.sln ./

# Kopiera projektfilen från rätt katalog
COPY ./MeTube-DevOps.Client/MeTube-DevOps.Client/*.csproj ./MeTube-DevOps.Client/

# Kör restore
RUN dotnet restore MeTube-DevOps.Client/MeTube-DevOps.Client.csproj

# Kopiera hela projektet
COPY ./MeTube-DevOps.Client/MeTube-DevOps.Client/ /app/MeTube-DevOps.Client/

# Bygg och kör
# CMD ["dotnet", "run", "--project", "/app/MeTube-DevOps.Client/MeTube-DevOps.Client.csproj"]
CMD ["dotnet", "MeTube-DevOps.Client.dll"]

