apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers: 
      - name: gateway
        image: gateway:1
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 200m       
            memory: 256Mi     
          limits:
            cpu: 500m         
            memory: 512Mi    
        env:
        - name: METUBE_GATEWAY_PORT
          value: "8080"
        - name: METUBE_USERSERVICE_SCHEME
          value: "http"
        - name: METUBE_USERSERVICE_HOST
          value: "metube-user"
        - name: METUBE_USERSERVICE_PORT
          value: "5000"
        ports:
        - containerPort: 8080
        # Enhanced health checks with longer timeouts
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60  # Increased from 30
          periodSeconds: 15        # Increased from 10
          timeoutSeconds: 5        # Added timeout
          failureThreshold: 3      # Added explicit failure threshold
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30  # Increased from 15
          periodSeconds: 10        # Increased from 5
          timeoutSeconds: 3        # Added timeout
          failureThreshold: 3      # Added explicit failure threshold
---
#external access 1 for gateway
apiVersion: v1
kind: Service
metadata:
  name: metube-gateway
spec:
  selector:
    app: gateway
  # type: NodePort
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5010
      targetPort: 8080

# Secondary service for internal compatibility
---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  selector:
    app: gateway
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5010
      targetPort: 8080



---
# Horizontal Pod Autoscaler for gateway
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-gateway
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gateway
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target: 
          type: Utilization
          averageUtilization: 50
  behavior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Pods
            value: 5
            periodSeconds: 300
      scaleUp:
        stabilizationWindowSeconds: 300
        policies:
          - type: Pods
            value: 5
            periodSeconds: 300
        selectPolicy: Max
          