apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  labels:
    app: userservice

spec:
  replicas: 1
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: metube-user
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 500m
          ports:
            - containerPort: 5000
          env:
            - name: DB_CONNECTION_STRING
              value: "Server=metube-user-db,1433;Database=MeTubeUserDb;User Id=sa;Password=YourSecretPass123;TrustServerCertificate=True"
          volumeMounts:
            - name: data
              mountPath: /app/data
      volumes:
        - name: data
          emptyDir: {}

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-userservice
  spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: userservice
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 70
    - type: Resource
      resource:
        name: memory
        target: 
          type: Utilization
          averageUtilization: 70
  behvarior:
      scaleDown:
        stabilizationWindowSeconds: 300
        policies:
          - type: Pods
            value: 5
            periodSeconds: 300
      scaleUp:
        stabilizationWindowSeconds: 300
        policies:
          - type: Pods
            value: 5
            periodSeconds: 300
        selectPolicy: Max