name: Client CI Pipeline

on:
  push:
    branches:
      - Pipeline-Integration
    paths:
      - MeTube-DevOps.Client/**
  pull_request:
    branches:
      - Pipeline-Integration
    paths:
      - MeTube-DevOps.Client/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Verify Docker Installation
        run: docker --version

      - name: Create Client CI Dockerfile
        run: |
          cat <<EOF > ci.client.Dockerfile
          FROM mcr.microsoft.com/dotnet/sdk:9.0
          WORKDIR /app
          EXPOSE 8080
          
          COPY MeTube-DevOps.Client/*.csproj MeTube-DevOps.Client/
          COPY MeTube-DevOps.Client/MeTube-DevOps.Client.sln .

          RUN dotnet restore

          COPY . .

          ENV ASPNETCORE_URLS=http://+:8080

          CMD ["dotnet", "run", "--project", "MeTube-DevOps.Client/MeTube-DevOps.Client.csproj"]
          EOF

      - name: Build Docker image
        run: docker build -t client-ci -f ci.client.Dockerfile .

      - name: Cleanup
        if: always()
        run: docker system prune -f
