name: Client CI Pipeline

on:
  push:
    branches:
      - main
    paths:
      - MeTube-DevOps.Client/**
  pull_request:
    branches:
      - main
    paths:
      - MeTube-DevOps.Client/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Verify Docker Installation
        run: docker --version

      - name: Create Client CI Dockerfile
        run: |
          cat <<EOF > ci.client.Dockerfile
          FROM mcr.microsoft.com/dotnet/sdk:9.0
          WORKDIR /app

          # Copy solution and project files first
          COPY MeTube-DevOps.Client/*.sln ./
          COPY MeTube-DevOps.Client/MeTube-DevOps.Client/*.csproj ./MeTube-DevOps.Client/

          # Restore dependencies
          RUN dotnet restore

          # Copy the rest of the code
          COPY . .

          # Build the project
          RUN dotnet build MeTube-DevOps.Client --configuration Release
          EOF

      - name: Build Docker image
        run: docker build -t client-ci -f ci.client.Dockerfile .

      - name: Cleanup
        if: always()
        run: docker system prune -f
