name: Deploy MeTube Client to Azure

on:
  workflow_dispatch:
    inputs:
      imageVersion:
        description: 'Image Version'
        required: true
        default: 'latest'

env:
  REGISTRY_HOST: ${{ secrets.DOCKER_USERNAME }}
  REGISTRY_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  IMAGE_NAME: client
  MICROSERVICE_NAME: client
  MICROSERVICE_DIRECTORY: MeTube-DevOps.Client
  DOCKERFILE_NAME: Dockerfile-Client-prod
  K8S_MANIFEST_PATH: ./scripts/local-k8-cluster/client.yml
  IMAGE_VERSION: ${{ github.event.inputs.imageVersion }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Docker Login
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Build image
        run: |
          chmod +x ./scripts/ci-cd/build-image.sh
          ./scripts/ci-cd/build-image.sh
      
      - name: Push image
        run: |
          chmod +x ./scripts/ci-cd/push-image.sh
          ./scripts/ci-cd/push-image.sh
        env:
          REGISTRY_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
      
      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | tr -d ' ' | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config current-context
      
      - name: Deploy to AKS
        run: |
          chmod +x ./scripts/ci-cd/deploy.sh
          ./scripts/ci-cd/deploy.sh