name: Integrate MeTube-DevOps.UserService

on:
  push:
    branches: [ SSCITEST ]
    paths:
      - MeTube-DevOps.UserService/**
  pull_request:
    branches: [ SSCITEST ]
    paths:
      - MeTube-DevOps.UserService/**
  workflow_dispatch:

jobs:
  integrate:
    runs-on: ubuntu-latest
    
    env:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://localhost:5218"
      ConnectionStrings__DefaultConnection: "Server=localhost;Database=MeTubeUserDb;User Id=sa;Password=YourSecretPass123;TrustServerCertificate=True;Encrypt=False;Connect Timeout=30"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Start SQL Server
        run: |
          docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=YourSecretPass123" \
            -e "MSSQL_PID=Express" \
            --name sql-server \
            -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest

      - name: Verify SQL Server
        run: |
          echo "Waiting for SQL Server to start..."
          for i in {1..30}; do
            if docker exec sql-server /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourSecretPass123 -Q "SELECT @@VERSION" -C; then
              echo "SQL Server is ready!"
              break
            fi
            echo "Attempt $i: Waiting for SQL Server to initialize..."
            sleep 5
            if [ $i -eq 30 ]; then
              echo "SQL Server failed to initialize. Checking logs..."
              docker logs sql-server
              exit 1
            fi
          done
      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.101

      - name: Check appsettings.json
        run: |
          echo "Checking API configuration..."
          cat MeTube-DevOps.UserService/MeTube-DevOps.UserService/appsettings.json
          cat MeTube-DevOps.UserService/MeTube-DevOps.UserService/appsettings.Development.json

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef
          
      - name: Apply Migrations
        run: |
          cd MeTube-DevOps.UserService/MeTube-DevOps.UserService
          dotnet ef database update --verbose
      
      - name: Build Solution
        run: |
          dotnet build MeTube-DevOps.UserService

      - name: Install Playwright browsers
        run: |
          cd MeTube-DevOps.UserService
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install
      
      - name: Run directly with tests
        run: |
          cd MeTube-DevOps.UserService
          dotnet test