name: Integrate MeTube-DevOps.UserService

on:
  push:
    branches: [ SSCITEST ]
    paths:
      - MeTube-DevOps.UserService/**
  pull_request:
    branches: [ SSCITEST ]
    paths:
      - MeTube-DevOps.UserService/**
  workflow_dispatch:

jobs:
  integrate:
    runs-on: ubuntu-latest
    
    env:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://localhost:5218"
      DB_CONNECTION_STRING: "Server=localhost;Database=MeTubeUserDb;User Id=sa;Password=YourSecretPass123;TrustServerCertificate=True;Connect Timeout=30"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Start SQL Server
        run: |
          docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=YourSecretPass123" \
            -e "MSSQL_PID=Express" \
            -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest
      
      - name: Verify SQL Server
        run: |
          echo "Waiting for SQL Server to start..."
          for i in {1..30}; do
            if docker exec $(docker ps -q) /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourSecretPass123 -Q "SELECT @@VERSION"; then
              echo "SQL Server is ready!"
              break
            fi
            echo "Attempt $i: Waiting for SQL Server..."
            sleep 5
            if [ $i -eq 30 ]; then
              echo "SQL Server failed to start. Checking logs..."
              docker logs $(docker ps -q)
              exit 1
            fi
          done
      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.101

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef
          
      - name: Apply Migrations
        run: |
          cd MeTube-DevOps.UserService/MeTube-DevOps.UserService
          dotnet ef database update --verbose
      
      - name: Build Solution
        run: dotnet build MeTube-DevOps.UserService
      
      - name: Run UserService
        run: |
          cd MeTube-DevOps.UserService/MeTube-DevOps.UserService
          nohup dotnet run > userservice.log 2>&1 &
          
      - name: Wait for UserService
        run: |
          echo "Waiting for UserService to start..."
          for i in {1..30}; do
            if curl -sSf http://localhost:5218/health > /dev/null 2>&1; then
              echo "UserService is ready!"
              break
            fi
            echo "Attempt $i: Waiting for UserService..."
            sleep 5
            if [ $i -eq 30 ]; then
              echo "UserService failed to start. Checking logs..."
              cat userservice.log
              exit 1
            fi
          done
      
      - name: Test
        run: dotnet test MeTube-DevOps.UserService