name: Integrate MeTube-DevOps.UserService

on:
  push:
    branches:
      - main
    paths:
      - MeTube-DevOps.UserService/**
  pull_request:
    branches:
      - main
    paths:
      - MeTube-DevOps.UserService/**
  workflow_dispatch:

jobs:
  integrate:
    runs-on: ubuntu-latest
    
    services:
      # Add SQL Server service container
      sql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: YourSecretPass123
        ports:
          - 1433:1433
        options: >-
          --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourSecretPass123 -Q 'SELECT 1'" 
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://localhost:5218"
      DB_CONNECTION_STRING: "Server=localhost,1433;Database=MeTubeUserDb;User Id=sa;Password=YourSecretPass123;TrustServerCertificate=True"
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.101

      # Install EF Core CLI
      - name: Install EF Core CLI
        run: |
          dotnet tool install --global dotnet-ef
          
      # Apply database migrations
      - name: Apply Migrations
        run: |
          cd MeTube-DevOps.UserService/MeTube-DevOps.UserService
          dotnet ef database update

      # Build the solution
      - name: Build Solution
        run: dotnet build MeTube-DevOps.UserService

      # Run the UserService in background
      - name: Run UserService
        run: |
          cd MeTube-DevOps.UserService/MeTube-DevOps.UserService
          dotnet run &
          
      # Check if service is up by polling health endpoint
      - name: Wait for UserService
        run: |
          for i in {1..30}; do
            curl -s -o /dev/null -w "%{http_code}" http://localhost:5218/health | grep 200 && break
            sleep 2
          done

      # Run tests
      - name: Test
        run: dotnet test MeTube-DevOps.UserService