name: Integrate MeTube-DevOps.UserService

on:
  push:
    branches: [ SSCITEST ]
    paths:
      - MeTube-DevOps.UserService/**
  pull_request:
    branches: [ SSCITEST ]
    paths:
      - MeTube-DevOps.UserService/**
  workflow_dispatch:

jobs:
  integrate:
    runs-on: ubuntu-latest
    
    env:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://localhost:5218"
      ConnectionStrings__DefaultConnection: "Server=localhost;Database=MeTubeUserDb;User Id=sa;Password=YourSecretPass123;TrustServerCertificate=True;Encrypt=False;Connect Timeout=30"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Start SQL Server
        run: |
          docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=YourSecretPass123" \
            -e "MSSQL_PID=Express" \
            --name sql-server \
            -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest

      - name: Verify SQL Server
        run: |
          echo "Waiting for SQL Server to start..."
          for i in {1..30}; do
            if docker exec sql-server /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P YourSecretPass123 -Q "SELECT @@VERSION" -C; then
              echo "SQL Server is ready!"
              break
            fi
            echo "Attempt $i: Waiting for SQL Server to initialize..."
            sleep 5
            if [ $i -eq 30 ]; then
              echo "SQL Server failed to initialize. Checking logs..."
              docker logs sql-server
              exit 1
            fi
          done
      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.101

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef
          
      - name: Apply Migrations
        run: |
          cd MeTube-DevOps.UserService/MeTube-DevOps.UserService
          dotnet ef database update --verbose
      
      - name: Build Solution
        run: |
          dotnet build MeTube-DevOps.UserService

      - name: Install Playwright browsers
        run: |
          cd MeTube-DevOps.UserService
          dotnet tool install --global Microsoft.Playwright.CLI
          playwright install
      
      - name: Run Unit Tests
        run: |
          cd MeTube-DevOps.UserService
          dotnet test MeTube-DevOps.UserService.UnitTests
      
      # Create a temporary Program file for CI that removes the health check
      - name: Prepare Service for CI
        run: |
          cd MeTube-DevOps.UserService/MeTube-DevOps.UserService
          # Create a backup of the original Program.cs
          cp Program.cs Program.cs.bak
          # Create a modified version without the health check mapping
          sed '/app.MapHealthChecks/d' Program.cs > Program.cs.temp
          mv Program.cs.temp Program.cs
          
      - name: Start UserService
        run: |
          cd MeTube-DevOps.UserService/MeTube-DevOps.UserService
          # Pass the connection string directly
          export ConnectionStrings__DefaultConnection="Server=localhost;Database=MeTubeUserDb;User Id=sa;Password=YourSecretPass123;TrustServerCertificate=True;Encrypt=False;Connect Timeout=30"
          nohup dotnet run --urls="http://0.0.0.0:5218" > userservice.log 2>&1 &
          echo $! > /tmp/userservice.pid
          
          # Wait for service to start by checking an existing API endpoint
          echo "Waiting for UserService to start..."
          for i in {1..30}; do
            # Try to hit the swagger endpoint instead of health
            if curl -s http://localhost:5218/swagger/index.html > /dev/null; then
              echo "UserService is ready!"
              break
            fi
            
            if [ $i -eq 10 ] || [ $i -eq 20 ]; then
              echo "Checking logs after attempt $i:"
              tail -20 userservice.log
              echo "Process status:"
              ps -p $(cat /tmp/userservice.pid) || echo "Process not running!"
            fi
            
            echo "Attempt $i: Waiting for UserService..."
            sleep 2
            
            if [ $i -eq 30 ]; then
              echo "UserService failed to start. Full logs:"
              cat userservice.log
              exit 1
            fi
          done
      
      - name: Run Integration Tests
        run: |
          cd MeTube-DevOps.UserService
          dotnet test MeTube-DevOps.UserService.IntegrTests
        
      - name: Cleanup
        if: always()
        run: |
          if [ -f /tmp/userservice.pid ]; then
            kill $(cat /tmp/userservice.pid) || true
            echo "UserService stopped"
          fi
          docker stop sql-server || true
          docker rm sql-server || true