name: Integrate MeTube-DevOps.UserService

on:
  push:
    branches: [ SSCITEST ]
    paths:
      - MeTube-DevOps.UserService/**
  pull_request:
    branches: [ SSCITEST ]
    paths:
      - MeTube-DevOps.UserService/**
  workflow_dispatch:

jobs:
  integrate:
    runs-on: ubuntu-latest
    
    env:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://localhost:5218"
      DB_CONNECTION_STRING: "Server=localhost;Database=MeTubeUserDb;User Id=sa;Password=YourSecretPass123;TrustServerCertificate=True;Connect Timeout=30"
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Start SQL Server
        run: |
          docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=YourSecretPass123" \
            -e "MSSQL_PID=Express" \
            --name sql-server \
            -p 1433:1433 -d mcr.microsoft.com/mssql/server:2019-latest

      - name: Debug SQL Server container
        run: |
          echo "Checking if container is running..."
          docker ps
          
          echo "Checking container logs..."
          docker logs sql-server
          
          echo "Exploring container paths..."
          docker exec sql-server ls -la /opt || echo "No /opt directory"
          docker exec sql-server find / -name "sqlcmd" 2>/dev/null || echo "sqlcmd not found"
      
      - name: Verify SQL Server with TCP check
        run: |
          echo "Waiting for SQL Server port to be ready..."
          for i in {1..30}; do
            if nc -z localhost 1433; then
              echo "SQL Server port is open!"
              break
            fi
            echo "Attempt $i: Waiting for SQL Server port..."
            sleep 5
            if [ $i -eq 30 ]; then
              echo "SQL Server port not available. Checking logs..."
              docker logs sql-server
              exit 1
            fi
          done
      
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.101

      - name: Install SQL Tools
        run: |
          echo "Installing SQL tools for verification..."
          apt-get update && apt-get install -y unixodbc-dev
          curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
          apt-get update
          ACCEPT_EULA=Y apt-get install -y msodbcsql17 mssql-tools
          echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
          export PATH="$PATH:/opt/mssql-tools/bin"

      - name: Test SQL Connection
        run: |
          echo "Testing SQL connection from host..."
          /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourSecretPass123 -Q "SELECT @@VERSION"

      - name: Install EF Core CLI
        run: dotnet tool install --global dotnet-ef
          
      - name: Apply Migrations
        run: |
          cd MeTube-DevOps.UserService/MeTube-DevOps.UserService
          dotnet ef database update --verbose
      
      - name: Build Solution
        run: dotnet build MeTube-DevOps.UserService
      
      - name: Run UserService
        run: |
          cd MeTube-DevOps.UserService/MeTube-DevOps.UserService
          nohup dotnet run > userservice.log 2>&1 &
          
      - name: Wait for UserService
        run: |
          echo "Waiting for UserService to start..."
          for i in {1..30}; do
            if curl -sSf http://localhost:5218/health > /dev/null 2>&1; then
              echo "UserService is ready!"
              break
            fi
            echo "Attempt $i: Waiting for UserService..."
            sleep 5
            if [ $i -eq 30 ]; then
              echo "UserService failed to start. Checking logs..."
              cat userservice.log
              exit 1
            fi
          done
      
      - name: Test
        run: dotnet test MeTube-DevOps.UserService